<<: !include {file: common.yaml, vars: {node_id: 1, peer_node_id: 2}}

wifi:
  <<: !include {file: wifi.yaml}
  manual_ip:
    static_ip: 192.168.1.201
    subnet: 255.255.255.0
    gateway: 192.168.1.1
